[default]

MASK_RESULT_JSON = {"text" = "", "result" = ""}

# INICIANDO OS PERCENTUAIS DE MATCH DEFAULT
DEFAULT_PERCENTUAL_MATCH = 82

# DEFININDO SE DEVE HAVER PRÉ PROCESSAMENTO DOS ITENS ANTES DO CÁLCULO DE SEMELHANÇA
DEFAULT_PRE_PROCESSING = false

# INICIANDO A VARIÁVEL QUE CONTÉM O LIMIT NA CHAMADA DE MÁXIMAS SIMILARIDADES
DEFAULT_LIMIT_RESULT_BEST_SIMILAR = 1

[development]
